version: '2'
services:
  app:
    build:
      context: ./
    ports:
      - '8081:80'
    environment:
      APP_ENV: local
      DB_PORT: 5432
      DB_HOST: database
      AWS_REGION: us-west-2
      ROOT_DIR: /app/server/public
    working_dir: /app
    volumes:
      - ./server:/app/server
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    networks:
      - lnchbx
  database:
    image: postgres
    environment:
      POSTGRES_DB: lnchbx
      POSTGRES_USER: lnchbx
      POSTGRES_PASSWORD: lnchbx
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '54320:5432'
    networks:
      - lnchbx
volumes:
  dbdata:
networks:
  lnchbx:
    driver: bridge
